# Generated by Django 3.1.3 on 2020-11-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201123_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='phone',
        ),
    ]
